"""Crazy Penguin Wars art pipeline: builds every model, texture and icon procedurally with Blender (bpy module).

Usage (from the repo root):
    python3 Blender/scripts/build_all.py                 # everything (models, textures, icons, docs, verify)
    python3 Blender/scripts/build_all.py models          # all models only
    python3 Blender/scripts/build_all.py penguin clothes # some steps
    python3 Blender/scripts/build_all.py icons:Weapons,Clothes   # some icon sections
Steps: penguin clothes weapons missiles props env textures icons docs verify  (models = the first six)
Env: CPW_SAMPLES=32 (Cycles samples for icons).
"""
import os
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import bpy  # noqa: E402,F401

import common as C  # noqa: E402

MODEL_STEPS = ["penguin", "clothes", "weapons", "missiles", "props", "env"]
ALL_STEPS = MODEL_STEPS + ["textures", "icons", "docs", "verify"]


def step(name, arg=None):
    t = time.time()
    if name == "penguin":
        import penguin
        penguin.run()
    elif name == "clothes":
        import clothes
        clothes.run()
    elif name == "weapons":
        import weapons
        weapons.run()
    elif name == "missiles":
        import missiles
        missiles.run()
    elif name == "props":
        import props
        props.run()
    elif name == "env":
        import env
        env.run()
    elif name == "textures":
        import textures
        textures.run()
    elif name == "icons":
        import icons
        icons.run(arg.split(",") if arg else None)
    elif name == "docs":
        write_docs()
    elif name == "verify":
        verify()
    else:
        raise SystemExit("unknown step " + name)
    print("== %s done in %.1fs" % (name, time.time() - t), flush=True)


def verify():
    """Re-import the penguin FBX and check size and orientation in Unity terms."""
    import verify_fbx
    lo, hi, parts = verify_fbx.verify(os.path.join(C.MODELS, "Penguin", "Penguin.fbx"), verbose=False)
    size = hi - lo
    beak = (parts["Beak"][0] + parts["Beak"][1]) / 2
    belly = (parts["Belly"][0] + parts["Belly"][1]) / 2
    ok = abs(size.y - 2.6) < 0.2 and lo.y > -0.1 and beak.x > 0.2 and belly.z < -0.1
    print("[verify] Penguin.fbx Unity size (%.2f, %.2f, %.2f), feet y=%.2f, beak x=%.2f (+X = facing right), belly z=%.2f "
          "(-Z = towards camera): %s" % (size.x, size.y, size.z, lo.y, beak.x, belly.z, "OK" if ok else "FAILED"))
    lo, hi, parts = verify_fbx.verify(os.path.join(C.MODELS, "Weapons", "MiniBazooka.fbx"), verbose=False)
    mz = parts.get("Muzzle")
    print("[verify] MiniBazooka.fbx x range %.2f..%.2f, Muzzle at x=%.2f: %s" % (
        lo.x, hi.x, mz[0].x if mz else float("nan"), "OK" if mz and mz[0].x > 0.4 else "FAILED"))
    for wid in ("HeatSeeker", "GreyGoo", "ChocoCannon"):
        lo, hi, parts = verify_fbx.verify(os.path.join(C.MODELS, "Weapons", wid + ".fbx"), verbose=False)
        mz = parts.get("Muzzle")
        good = bool(mz) and mz[0].x > 0.3 and abs(mz[0].x - hi.x) < 0.25
        print("[verify] %s.fbx x range %.2f..%.2f, Muzzle at x=%.2f: %s" % (
            wid, lo.x, hi.x, mz[0].x if mz else float("nan"), "OK" if good else "FAILED"))
        ok = ok and good
    if not ok:
        raise SystemExit(1)


def _listing(folder, ext):
    p = os.path.join(C.RES, folder)
    if not os.path.isdir(p):
        return []
    return sorted(os.path.splitext(f)[0] for f in os.listdir(p) if f.endswith(ext))


def write_docs():
    import env
    import missiles
    import penguin
    lines = []
    w = lines.append
    w("# Art (Blender pipeline)")
    w("")
    w("All art is generated procedurally by `Blender/scripts/*.py` with Blender 4.2 as a Python module (`import bpy`).")
    w("Rebuild everything with `python3 Blender/scripts/build_all.py` (about 10 minutes on 4 CPU cores; see the script")
    w("docstring for single steps such as `build_all.py clothes` or `build_all.py icons:Weapons`). The .blend sources are")
    w("saved to `Blender/blend/` (one file per category, one collection per asset). This file is regenerated by the `docs` step.")
    w("")
    w("## Conventions")
    w("- 1 Unity unit = 20 Flash pixels. Blender scripts model in a *game frame*: +X right, +Z up, -Y towards the camera.")
    w("  FBX export: `axis_forward='-Z', axis_up='Y', bake_space_transform=True, apply_scale_options='FBX_SCALE_ALL'`, modifiers")
    w("  applied, MESH+EMPTY only. Unity mirrors X on import, so the scripts turn the scene 180 degrees around Z just before")
    w("  exporting; in Unity +X is right, +Y up and -Z faces the camera. `build_all.py verify` re-imports the penguin and checks it.")
    w("- Flat colors only: one material per color, color in the Principled base color (exported as sRGB values so")
    w("  `Mats.ApplyToon` reproduces them). Team color: the penguin's `Scarf` uses a white material named `Team` (tint it).")
    w("- Poly budget: penguin about 4k triangles, clothes/weapons/props under 1.5k.")
    w("")
    w("## Penguin (`Models/Penguin/Penguin.fbx`)")
    w("About %.1f units tall, feet at the origin, beak towards +X, belly towards -Z (turned %d degrees from facing the camera)." % (
        penguin.HEIGHT, penguin.YAW))
    w("Parts (origins at their joints): Body (pivot at the bottom), Belly, Head (pivot at the neck), Beak, EyeL, EyeR, PupilL, PupilR,")
    w("FlipperL, FlipperR (pivots at the shoulders), FootL, FootR (pivots at the ankles), Scarf. Empties: HeadSocket (head center),")
    w("ChestSocket (body axis), FootSocketL/R (ankles), HandSocket (tip of the right flipper, the one nearer the camera).")
    w("**Every part is a root object in the FBX** (Blender 4.2's exporter writes wrong transforms for objects nested two levels")
    w("deep when `bake_space_transform` is on). `PenguinAvatar` rebuilds this hierarchy at runtime (`worldPositionStays`):")
    w("")
    for k, v in penguin.HIERARCHY.items():
        w("- %s -> %s" % (k, v))
    w("")
    w("## Clothes (`Models/Clothes/{Bonus id}.fbx`)")
    w("Origin = socket. Head items -> HeadSocket, chest items -> ChestSocket, feet items -> FootSocketL and the same model on")
    w("FootSocketR (feet items are symmetric around the foot axis, no mirroring needed). Already turned like the penguin, so attach")
    w("with identity local rotation. Icons: `Icons/Clothes/{id}.png`.")
    w("")
    w(", ".join(_listing("Models/Clothes", ".fbx")))
    w("")
    w("## Weapons (`Models/Weapons/{WeaponGraphic id}.fbx`)")
    w("Grip at the origin, barrel along +X, child empty `Muzzle` at the tip. Thrown items are held slightly above the origin.")
    w("Icons: `Icons/Weapons/{WeaponIcon id}.png`.")
    w("")
    w(", ".join(_listing("Models/Weapons", ".fbx")))
    w("")
    w("## Missiles (`Models/Missiles/{MissileGraphic id}.fbx`)")
    w("Centered, nose towards +X. Variants share a mesh (the same FBX copied under each id):")
    w("")
    by = {}
    for mid, shp in missiles.MAP.items():
        by.setdefault(shp, []).append(mid)
    for shp, mids in sorted(by.items()):
        w("- %s: %s" % (shp, ", ".join(sorted(mids))))
    w("- extra alias: Caltrop (same as Caltrops)")
    w("")
    w("## Props (`Models/Props/{id}.fbx`)")
    w("Level objects reproduce the original physics shapes from `Blender/data/dynamicobjects/{Material}.xml` (copied from")
    w("cpw-server/assets/dynamicobjects): Unity x = px/20, Unity y = -py/20 (Flash y points down), origin = physics body origin,")
    w("depth centered on z=0. Pickups: Crate (with child `Parachute`), HealthCrate, AmmoCrate, PointsCrate, Treasure (all 1.3 units,")
    w("centered), Parachute (canopy rim at the origin, strings end 1.55 below), Mine, FireMine (about 2 units wide), Coin (0.85, faces -Z).")
    w("")
    w(", ".join(_listing("Models/Props", ".fbx")))
    w("")
    w("## Environment (`Models/Env/{Theme}_{Name}.fbx`)")
    w("Origin at the bottom center, for the parallax background (names with cloud/sun go to the sky layer; peak/hill/mesa/dune/berg")
    w("to the far layer; the rest to the near layer).")
    w("")
    for name in env.ENV:
        w("- %s" % name)
    w("")
    w("## Icons (`Icons/...`, 256x256 PNG, transparent, outline + drop shadow)")
    for cat in ("Weapons", "Boosters", "Clothes", "Trophies", "Emoticons", "Slot", "Ui", "Hud", "Crafting", "Achievements"):
        names = _listing("Icons/" + cat, ".png")
        w("- **%s** (%d): %s" % (cat, len(names), ", ".join(names) if len(names) <= 60 else ", ".join(names[:12]) + ", ..."))
    w("- `Ui/app_icon.png` is 1024x1024 and opaque. Achievements are 192x192 (group emblem + tier color).")
    w("")
    w("## Textures")
    w("- `Textures/Terrain/{id}.png`: seamless 256x256 tiles: " + ", ".join(_listing("Textures/Terrain", ".png")))
    w("- `Textures/Sky/{theme}.png`: 4x256 vertical gradients (top row = top of the sky): " + ", ".join(_listing("Textures/Sky", ".png")))
    w("")
    w("## Code")
    w("- `Scripts/Art/PenguinAvatar.cs`: spawns the penguin, rebuilds the hierarchy, procedural animation per `AvatarState`,")
    w("  clothes on sockets, held weapon on HandSocket (Muzzle), team-colored scarf, hit flash (`_Flash` via MaterialPropertyBlock),")
    w("  emote bubble. Works with primitive fallbacks when models are missing.")
    w("- `Scripts/Art/ArtCatalog.cs`: id -> model/icon path helpers with fallbacks.")
    path = os.path.join(C.ROOT, "Docs", "ART.md")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print("[docs] wrote", path)


def main(argv):
    steps = argv or ALL_STEPS
    expanded = []
    for s in steps:
        if s == "models":
            expanded += MODEL_STEPS
        elif s == "all":
            expanded += ALL_STEPS
        else:
            expanded.append(s)
    t = time.time()
    for s in expanded:
        name, _, arg = s.partition(":")
        step(name, arg or None)
    # keep the Caltrop alias used by Weapons/Deployables
    src = os.path.join(C.MODELS, "Missiles", "Caltrops.fbx")
    if os.path.exists(src):
        import shutil
        shutil.copyfile(src, os.path.join(C.MODELS, "Missiles", "Caltrop.fbx"))
    print("== all done in %.0fs" % (time.time() - t))


if __name__ == "__main__":
    main(sys.argv[1:])
