#!/usr/bin/env python3
"""Generate OriginalAssets/ID_MAP.md (game config id -> extracted file) and OriginalAssets/INVENTORY.md
(per SWF: symbols, frames, bitmaps, size) from the index.json files written by extract.py.
Usage: build_tables.py [--out OriginalAssets] [--config Assets/CPW/Resources/Data/config.json]"""
import argparse, glob, json, os

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, '..', '..'))
TABLES = ['WeaponGraphic', 'WeaponIcon', 'MissileGraphic', 'FollowerGraphic', 'AnimationGraphic', 'BoosterIcon',
          'EmoticonGraphic', 'EmoticonIcon', 'LevelObjectGraphic', 'SlotMachineGraphic', 'BundleIcon', 'PlayerGraphic']


def dir_size(p):
    return sum(os.path.getsize(os.path.join(r, f)) for r, _, fs in os.walk(p) for f in fs)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--out', default=os.path.join(REPO, 'OriginalAssets'))
    ap.add_argument('--config', default=os.path.join(REPO, 'Assets/CPW/Resources/Data/config.json'))
    a = ap.parse_args()
    idx = {}
    for f in glob.glob(os.path.join(a.out, '*', '*', 'index.json')):
        d = json.load(open(f))
        idx[os.path.splitext(os.path.basename(d['swf']))[0]] = (os.path.relpath(os.path.dirname(f), a.out), d)

    def resolve(swf, export, anywhere=True):
        stem = os.path.splitext(os.path.basename(swf or ''))[0]
        if stem not in idx:
            return find_any(export) if anywhere else None
        r = lookup(idx[stem], export) or lookup(idx[stem], export + '_1')  # level objects: _1 intact, _2/_3 damaged
        return r or (find_any(export) if anywhere else None)

    def find_any(export):
        for v in idx.values():
            r = lookup(v, export)
            if r:
                return r + ' (in another SWF)'
        return None

    def lookup(entry, export):
        rel, d = entry
        s = d['symbols'].get(export)
        if s:
            return '%s/%s' % (rel, s['files'][0].split('/')[0]) + (' (%d frames)' % len(s['sequence']) if s.get('sequence') else '')
        for fn, b in d['bitmaps'].items():
            if b.get('linkage') == export or os.path.basename(fn)[:-4] == export:
                return '%s/%s' % (rel, fn)
        return None

    cfg = json.load(open(a.config))
    lines = ['# Config id -> original asset', '', 'Generated by `Tools/extract_original/build_tables.py` from '
             '`Assets/CPW/Resources/Data/config.json` (SWF + Export columns) and the `index.json` files. '
             'Paths are relative to `OriginalAssets/`. MISSING = the SWF or the symbol is not in the public repos.', '']
    total = found = 0
    for t in TABLES:
        rows = {k: v for k, v in cfg.get(t, {}).items() if k != '$DATA_TYPE' and isinstance(v, dict)}
        if not rows:
            continue
        lines += ['## %s (%d)' % (t, len(rows)), '', '| id | SWF | Export | file |', '|---|---|---|---|']
        for k, v in sorted(rows.items()):
            swf, ex = v.get('SWF'), v.get('Export')
            r = resolve(swf, ex) if ex else (idx.get(os.path.splitext(os.path.basename(swf or ''))[0], [None])[0])
            total += 1; found += bool(r)
            lines.append('| %s | %s | %s | %s |' % (k, swf, ex or '', r or 'MISSING'))
        lines.append('')
    # level themes
    lines += ['## LevelTheme', '', '| theme | background | landmass (terrain) | liquid |', '|---|---|---|---|']
    for k, v in sorted(cfg.get('LevelTheme', {}).items()):
        if k == '$DATA_TYPE':
            continue
        def stem(p):
            s = os.path.splitext(os.path.basename(p or ''))[0]
            return idx[s][0] if s in idx else ('MISSING ' + s if s else '')
        lines.append('| %s | %s | %s | %s |' % (k, stem(v.get('BackgroundSWF')), stem(v.get('LandmassSWF')),
                                               resolve(v.get('WaterSWF'), v.get('WaterExport')) or 'MISSING ' + str(v.get('WaterExport'))))
    lines += ['', 'Resolved %d of %d config graphics references.' % (found, total), '']
    open(os.path.join(a.out, 'ID_MAP.md'), 'w').write('\n'.join(lines))

    inv = ['# Inventory of extracted SWFs', '', '| folder | source SWF | zoom | linkage sprites | PNG files | frames (total) | bitmaps | size |',
           '|---|---|---|---|---|---|---|---|']
    for stem, (rel, d) in sorted(idx.items(), key=lambda x: x[1][0]):
        nf = sum(len(s['files']) for s in d['symbols'].values())
        ft = sum(s['frames_total'] for s in d['symbols'].values())
        inv.append('| %s | %s | %sx | %d | %d | %d | %d | %.1f MB |' % (rel, d['swf'], d['zoom'], len(d['symbols']), nf, ft,
                                                                    len(d['bitmaps']), dir_size(os.path.join(a.out, rel)) / 1e6))
    inv += ['', 'Total OriginalAssets size: %.1f MB' % (dir_size(a.out) / 1e6), '']
    for stem, (rel, d) in sorted(idx.items(), key=lambda x: x[1][0]):
        inv += ['## %s' % rel, '']
        inv.append(', '.join('`%s`%s' % (n, '(%d)' % s['frames_total'] if s['frames_total'] > 1 else '') for n, s in sorted(d['symbols'].items())) or '(no linkage sprites)')
        named = sorted(b['linkage'] for b in d['bitmaps'].values() if b.get('linkage'))
        if named:
            inv.append('\nNamed bitmaps: ' + ', '.join('`%s`' % n for n in named))
        inv.append('')
    open(os.path.join(a.out, 'INVENTORY.md'), 'w').write('\n'.join(inv))
    print('ID_MAP: %d/%d resolved' % (found, total))


if __name__ == '__main__':
    main()
